[build]
  publish = "dist"
  command = "pnpm run build"
  functions = "dist/src/server"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
included_files = ["!node_modules/.prisma/**"]